package com.example.covidstatetracker.models

class CoVidState : ArrayList<CoVidStateItem>()

data class CoVidStateItem(
    val checkTimeEt: String?,
    val commercialScore: Int?,
    val dataQualityGrade: String?,
    val date: Int?,
    val dateChecked: String?,
    val dateModified: String?,
    val death: Int?,
    val deathIncrease: Int?,
    val fips: String?,
    val grade: String?,
    val hash: String?,
    val hospitalized: Int?,
    val hospitalizedCumulative: Int?,
    val hospitalizedCurrently: Int?,
    val hospitalizedIncrease: Int?,
    val inIcuCumulative: Int?,
    val inIcuCurrently: Int?,
    val lastUpdateEt: String?,
    val negative: Int?,
    val negativeIncrease: Int?,
    val negativeRegularScore: Int?,
    val negativeScore: Int?,
    val negativeTestsViral: Int?,
    val onVentilatorCumulative: Int?,
    val onVentilatorCurrently: Int?,
    val pending: Int?,
    val posNeg: Int?,
    val positive: Int?,
    val positiveCasesViral: Int?,
    val positiveIncrease: Int?,
    val positiveScore: Int?,
    val positiveTestsViral: Int?,
    val recovered: Int?,
    val score: Int?,
    val state: String?,
    val total: Int?,
    val totalTestResults: Int?,
    val totalTestResultsIncrease: Int?,
    val totalTestsViral: Int?
)